# Generated by Django 4.2.7 on 2023-11-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trace_id', models.CharField(max_length=100)),
                ('span_id', models.CharField(max_length=100)),
                ('commit', models.CharField(max_length=100)),
                ('parentResourceId', models.CharField(max_length=100)),
            ],
        ),
    ]
