# Generated by Django 4.2.7 on 2023-11-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management', '0003_alter_log_level'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log',
            table='lis_table',
        ),
    ]
